spring:
  application:
    name: 'aws_projecto01'
  datasource:
    url: 'jdbc:mariadb://localhost:3306/aws_project01'
    username: 'username'
    password: 'password'

  jpa:
    hibernate:
      ddl-auto=update:
    datasource-platform: og.hibernate.dialect.MySQLInnoDBDialect