spring:
  application:
    name: 'aws_project01'
  datasource:
    url: ${DATABASE_URL:jdbc:mariadb://localhost:3306/aws_project01}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234567}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update